image: node:4

cache:
    paths:
      - node_modules/

stages:
    - test
    - build

test:
   tags:
       - texo
   stage: test
   script:
      - npm install
      - npm test

package:
    tags:
        - texo
    stage: build
    script:
        - npm install
    only:
        - tags
#    except:
#        - develop
    artifacts:
        name: f5-cloud-libs-"${CI_BUILD_TAG}"
        paths:
            - .
        expire_in: 10 mins
