image: node:4

cache:
    paths:
        - node_modules/

stages:
    - test
    - build

test:
    tags:
        - texo
    stage: test
    script:
        - echo Install and test
        - npm install
        - npm test

package:
    tags:
        - texo
    stage: build
    script:
        - echo Packaging
    only:
        - tags
#    except:
#        - develop
    artifacts:
        name: f5-cloud-libs"${CI_BUILD_TAG}"
        paths:
            - LICENSE
            - README.md
            - index.js
            - package.json
            - lib
            - scripts
            - node_modules
        expire_in: 10 mins
