image: node:4

stages:
    - test
    - package

test:
    tags:
        - docker-executor
    stage: test
    script:
        - npm install
        - npm test

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^release-.*/
        - triggers
    script:
        - npm run package
    artifacts:
        name: f5-cloud-libs-$CI_BUILD_REF
        paths:
            - dist/
