image: node:4

cache:
    paths:
      - node_modules/

stages:
    - test
    - build

test:
    tags:
        - texo
    stage: test
    script:
        - npm install
        - npm test
    only:
        - develop

package:
    tags:
        - texo
    stage: build
    script:
        - npm install
        - npm test
    only:
        - tags
#    except:
#        - develop
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_BUILD_TAG}"
        paths:
            - $CI_PROJECT_NAME
        expire_in: 10 mins
