#!/bin/sh
#
BRANCH=`git rev-parse --abbrev-ref HEAD`

echo "Running lint"
if ! npm run lint; then
    echo
    echo "Rejecting commit: Linting failed."
    echo
    exit 1
fi

echo "Running unit tests"
if ! npm run test -- --reporter minimal; then
    echo
    echo "Rejecting commit: Unit tests failed."
    echo
    exit 1
fi

echo "Generating docs"
npm run doc
git add USAGE.md

#if [[ "$BRANCH" != master && "$BRANCH" != release-* && "$BRANCH" != hf-* ]]; then
#    echo "Packaging"
#    npm run package
#    git add dist
#fi
